# Generated by Django 4.0.1 on 2022-04-19 14:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='client/')),
            ],
            options={
                'verbose_name': 'client',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=50)),
                ('head_title', models.CharField(max_length=50)),
                ('head_logo', models.ImageField(upload_to='content/head')),
                ('main_logo', models.ImageField(upload_to='content/main')),
                ('menu_bar_about', models.CharField(max_length=30)),
                ('menu_bar_services', models.CharField(max_length=30)),
                ('menu_bar_projects', models.CharField(max_length=30)),
                ('menu_bar_contact', models.CharField(max_length=30)),
                ('about_us_intro', models.CharField(blank=True, max_length=200)),
                ('about_us_description', models.TextField(blank=True, max_length=500)),
                ('services_intro', models.CharField(blank=True, max_length=200)),
                ('services_description', models.TextField(blank=True, max_length=500)),
                ('projects_intro', models.CharField(blank=True, max_length=200)),
                ('projects_description', models.TextField(blank=True, max_length=500)),
                ('client_intro', models.CharField(blank=True, max_length=200)),
                ('client_description', models.TextField(blank=True, max_length=500)),
                ('team_intro', models.CharField(blank=True, max_length=200)),
                ('team_description', models.TextField(blank=True, max_length=500)),
                ('contact_intro', models.CharField(blank=True, max_length=200)),
                ('contact_description', models.TextField(blank=True, max_length=500)),
                ('message_title', models.CharField(blank=True, max_length=100)),
                ('message_name_placeholder', models.CharField(blank=True, max_length=100)),
                ('message_email_placeholder', models.CharField(blank=True, max_length=100)),
                ('message_subject_placeholder', models.CharField(blank=True, max_length=100)),
                ('message_placeholder', models.CharField(blank=True, max_length=100)),
                ('message_button', models.CharField(blank=True, max_length=50)),
                ('contact_info_title', models.CharField(blank=True, max_length=100)),
                ('contact_address_title', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.CharField(blank=True, max_length=500)),
                ('contact_email_title', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=300)),
                ('contact_phone_title', models.CharField(blank=True, max_length=50)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'content',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='project/')),
            ],
            options={
                'verbose_name': 'project',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_description', models.TextField(blank=True, max_length=200)),
                ('icon', models.ImageField(upload_to='service/')),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_description', models.TextField(blank=True, max_length=200)),
                ('icon', models.ImageField(upload_to='skill/')),
            ],
            options={
                'verbose_name': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_function', models.TextField(blank=True, max_length=100)),
                ('function_description', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(upload_to='team/')),
            ],
            options={
                'verbose_name': 'team',
            },
        ),
    ]
